cniEnabled: true
identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBijCCATCgAwIBAgIQNrMjlJM+DYm4e8HXTIMdbDAKBggqhkjOPQQDAjAlMSMw
  IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzA4MjMxMTM1
  MTBaFw0zMzA4MjAxMTM1MTBaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
  dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEYdMkL/Vzv+gJE3VC
  DmW0wPNnDTcgKqOJN//2Q1YBc3Jn3iMENHpqJld9zXI/J/jOU4FIf7BJsbV4TxwQ
  31azpKNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
  BBYEFHR9nP5wj2ajcq8eDys5KWXzIP9xMAoGCCqGSM49BAMCA0gAMEUCIHBua4K+
  z031NdiMMTKJkJx2Ru5S4CzwlxX8PKlg6rwhAiEA/5psJ/qJoQz7ZkR9ZaAFDRkJ
  3lAKlCmpimgU9BY3JHc=
  -----END CERTIFICATE-----
identity:
  issuer:
    tls:
      crtPEM: |
        ----BEGIN CERTIFICATE-----
        MIIBrzCCAVagAwIBAgIRANO0k9FxFNsb47V+K4+J9OEwCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwODIzMTEz
        NTEwWhcNMzMwODIwMTEzNTEwWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJk
        LmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR0b4mKaqcR
        JDaN2Qr851orVEZGkyUtR6lIzbzpvGXQcGkhUHpAw+3Ku8FcZnpLGc6RqQlehpp4
        K0DXURzZv+77o2MwYTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAd
        BgNVHQ4EFgQUx1DepsYP+G9ZesAxFuVVXs0hx7AwHwYDVR0jBBgwFoAUdH2c/nCP
        ZqNyrx4PKzkpZfMg/3EwCgYIKoZIzj0EAwIDRwAwRAIgV5HJU1djPLWvDkNBUjmc
        +XHast9fBmorsyxI1f6zuhACICKIMHKQblGHzFVOhmsloFBIM1UUN6XIv5ySLbsE
        FxtI
        -----END CERTIFICATE-----
      keyPEM: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEILfDkJA9AcgeN+jk9RzU1st/IBUFPA1Y9d1m0euVPtLxoAoGCCqGSM49
        AwEHoUQDQgAEdG+JimqnESQ2jdkK/OdaK1RGRpMlLUepSM286bxl0HBpIVB6QMPt
        yrvBXGZ6SxnOkakJXoaaeCtA11Ec2b/u+w==
        -----END EC PRIVATE KEY-----
